In [1]:
import numpy as np

n = 1
RTO = (1 * (n + 1) + 0.01 * abs(n - 99)) / 50

print(RTO)

while RTO < 1:
    n += 1
    RTO = (1 * (n + 1) + 0.01 * abs(n - 99)) / 50
    
print(n)

0.0596
49


In [6]:
CKPT_PATH = "./saved_model/model" + str(random.randint(1,101)) + ".h5"
print(CKPT_PATH)

./saved_model/model53.h5


In [2]:
import numpy as np
TEST_PATH = "./data/cifar10-batches-images-test.npy"
tmp = []
tmp = np.load(TEST_PATH)
print(tmp.shape) # (10000, 32, 32, 3)


(10000, 32, 32, 3)


In [3]:
import numpy as np

arr = []

for i in range(6):
    arr.append(i)
    
print(len(arr))

6


In [2]:
tmp = 30
blah = [x for x in range(30)]
print(blah)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]


In [2]:
for i in range(10):
    print("I can count from %d to 10" %i)

I can count from 0 to 10
I can count from 1 to 10
I can count from 2 to 10
I can count from 3 to 10
I can count from 4 to 10
I can count from 5 to 10
I can count from 6 to 10
I can count from 7 to 10
I can count from 8 to 10
I can count from 9 to 10


In [4]:
a = np.array([[2,3], [4,5]])
print(a.shape)

(2, 2)


In [6]:
a = np.reshape(a, [1,4])
print(a)

[[2 3 4 5]]


In [4]:
from __future__ import print_function
import torch
x = torch.empty(5,3)
print(x)

tensor([[3.0866e+29, 1.1824e+22, 7.0976e+22],
        [1.8515e+28, 4.1988e+07, 3.0357e+32],
        [7.7491e+26, 3.0357e+32, 6.3828e+28],
        [1.4603e-19, 1.8617e+25, 1.6212e-19],
        [1.8617e+25, 7.9438e+08, 3.2604e-12]])


In [5]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [6]:
x = torch.ones(2,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [7]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [8]:
z = y*y*3
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)


In [ ]:
out = z.mean()
print(z, out)
out.backward()

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [3]:
print(x.grad)

NameError: name 'x' is not defined